// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkebolhbjgyvoqkwrfup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrZWJvbGhiamd5dm9xa3dyZnVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5Nzc4NTIsImV4cCI6MjA2NzU1Mzg1Mn0.uKUXxMkCEBAZSYZ91HOjXk_FtOyJEMIID9oCZdIkHh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});